[package]
name = "bench"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anput = { version = "*", path = "../crates/_" }
rand = "0.9"
ittapi = "0.5"

[dev-dependencies]
criterion = "0.8"
hecs = "0.11"
shipyard = "0.11"

[[bench]]
name = "ecs"
harness = false